<?php
    $lang = array(
	    'en' => array(
			'title' => 'Keep your eyes on the clock',
			'name' => 'Escape Land',
			
			'button_no1' => 'Home',
			'button_no2' => 'Contact',
			'button_no3' => 'Rooms',
			'button_no4' => 'Log in',
			'button_no5' => 'Book now',
			
			'title_no1' => '4 incredible rooms',
			'content_no1' => 'We guarantee you will find a room to tackle with your imagination. Can you break out of these top rooms?',
			'title_no2' => 'About us',
			'title_no3' => 'What we offer',
			'content_no2' => 'Escape Land is a fun,new, team building real-life escape game entertainment concept, designed for small groups of 2-6 people. Your goal is simple:work together as a team and test your skills, to escape a locked room.
							Escapers must be observing and use their critical thinking skills to escape the rooms. Communication with your team members is the most important if you want to get out in time. See if you can keep cool and escape the room in under 60 minutes.',
	    
			'room_no1_name' => 'Nightmare',
			'room_no2_name' => 'Zombies Invasion',
			'room_no3_name' => 'Pirate Cave',
			'room_no4_name' => 'The Tomb',
			'room_no1_title' => 'Freddy Krueger is out to get you!',
			'room_no2_title' => 'Will you make it out alive?',
			'room_no3_title' => 'Ahoy, mate!',
			'room_no4_title' => 'Perceive the total Egyptian mummy experience!',
			'room_no1_desc' => 'The city is crippled by a wave of murders and attacks since the start of a research program called "Collective Dream". Somniphobia, or Fear of Sleeping, is the common factor which unites all the victims of the said phenomenon. A vision of a man with a burnt face and fingers protruding from the blades is what is haunting all the victims. They claim to be pursued by the horrific character. Get yourself caught in a trance of this frightful nightmare only to outtake the boogeyman and get yourself free of the bonds. But beware - this is not a game!',
			'room_no2_desc' => '2030 - The Fall Of Mankind. An epidemic - mutated Ebola Virus – has changed the chemical structure of a normal human body, turning it into a bloodthirsty Zombie, eradicating half of the Human Race. A known survivor, Dr. Anton Redkevych, a talented microbiologist, made a breakthrough - a vaccine for the current plague. Announcing that he has found the “CURE” on a common radio frequency, you and your team are dispatched for a search-and-rescue mission. You must retrieve the vaccine and the “Miracle Doctor” due to ceased communications without any probable cause. You only have an hour before the "SAFE WINDOW PERIOD" ends…',
			'room_no3_desc' => 'You sailed out on a mission commissioned by admiral Howell Davis to the Unknown Islands northwest of the Atlantic Ocean, in order to retrieve his treasure. Leaving the harbor behind and sailing on strange tides! You were attacked by pirates and most of the crew died. You and few others were taken as prisoners to the pirate cave. The pirates went on the prowl and this is your chance to get your freedom before they return. Dive into the world of pirates and become a part of a treasure hunting adrenaline-raising experience. Find the treasure, escape and discover the secret of Pirate Cave',
			'room_no4_desc' => 'Riddle of the Philosopher’s Stone embarks you on an expedition to the outskirts of an ancient town in Abusira, Egypt. This is where ancient myth reveals an underground pyramid said to be the whereabouts of the tomb of the great Pharaoh Nyuserre Ini of the 5th Dynasty. Rumor has it that the journey itself cost the lives of hundreds of expeditioners searching for hidden treasures. Venture upon the ancient maze and solve time-worn mechanisms to escape this horrendous ancient ruin, or let your mortal body becomes a keepsake of the tombs vengeance for culprits.',
			
			'login' => 'Login here',
			'user' => 'Username',
			'pass' => 'Password',
			'login_button' => 'Login',
			'logout_button' => 'Logout',
			'register' => 'Register here',
			'register_button' => 'Register',
			'greeting' => 'Welcome',
			
			'contact_title' => 'Contact us',
			'phone_no' => '004 0747 789 245',
			'address' => 'Timisoara B-dul Constantin Brancoveanu 53.',
			'e-mail' => 'office@exitgames.ro',
			'timetable' => 'Schedule',
			'slot' => '10:00 - 20:00',
			'closed' => 'Closed',
			'mon' => 'Monday',
			'tue' => 'Tuesday',
			'wed' => 'Wednesday',
			'thu' => 'Thursday',
			'fri' => 'Friday',
			'sat' => 'Saturday',
			'sun' => 'Sunday',
			
			'booking_title' => 'Please fill in the form',
			'name_field' => 'Name',
			'email_field' => 'E-mail',
			'phone_field' => 'Telephone',
			'room_field' => 'Room',
			'date_field' => 'Date',
			'hour_field' => 'Hour',
			'pers_field' => 'Number of participants',
			'price' => 'Prices',
			'participants' => '2-6 persons',
			'discount' => 'Happy Hour - before 5:00 PM',
			'price_no1' => '40 lei/person',
			'usual' => 'After 17:00 PM',
			'price_no2' => '50 lei/person',
			'when' => 'When to come?',
			'when_ans' => 'Come 15 minutes prior start of your session.',
			'what' => 'What to bring?',
			'what_ans' => 'Curiosity and a sharp mind!',
			'booking_ok' => 'Successfull reservation!',
			'total_price' => 'Total sum: '
			),
		
		'ro' => array(
			'title' => 'Fiti cu ochii pe ceas',
			'name' => 'Escape Land',
			
			'button_no1' => 'Home',
			'button_no2' => 'Contact',
			'button_no3' => 'Camere',
			'button_no4' => 'Log in',
			'button_no5' => 'Rezervati acum',
			
			'title_no1' => '4 camere incredibile',
			'content_no1' => 'Va garantam ca veti gasi o camera care sa va puna imaginatia la incercare! Oare veti reusi sa iesiti din camera in timp util?',
			'title_no2' => 'Despre noi',
			'title_no3' => 'Ce va oferim',
			'content_no2' => 'Scopul e simplu: lucrati in echipa, faceti apel la imaginatie si logica pentru a iesi din camera incuiata. Concurentii trebuie sa-si foloseasca simtul de observatie si gandirea critica pentru a rezolva ghicitoarea din camera. Comunicarea cu coechipierii este esentiala daca doriti sa va incadrati in timp. Pastrativa calmul si incercati sa dezlegati misterul in mai putin de 60 min.',
	
			'room_no1_name' => 'Cosmar',
			'room_no2_name' => 'Invazia zombilor',
			'room_no3_name' => 'Pestera piratilor',
			'room_no4_name' => 'Mormantul',
			'room_no1_title' => 'Freddy Krueger e pe urmele tale!',
			'room_no2_title' => 'Vei supravietui?',
			'room_no3_title' => 'Ahoy, camarade!',
			'room_no4_title' => 'Traieste experiente in Egipt!',
			'room_no1_desc' => 'Inca de la inceputul programului "Collective Dream" orasul e lovit de un val de atacuri si crime. Frica de somn este factorul care uneste toate victimele acestui fenomen. Viziunea unui barbat cu fata arsa si degete precum niste lame ascutite bantuie toate victimele. Acestea sustin ca sunt urmarite de personajul infiorator. Lasati-va prinsi in transa acestui cosmar pentru a-l invinge pe antagonist si a va elibera. Fiti insa cu bagare de seama - acesta nu este un joc!',
			'room_no2_desc' => '2030 - Declinul omenirii. O epidemie - mutatie a virusului Ebola - a alterat structura chimica normala a corpului uman, transformand indivizii in zombie si eradicand jumatate rasa umana. Dr. Anton Redkevych, un cunoscut supravietuitor si talentat microbiologist, a facut o descoperire - un vaccin antidot pentru aceasta boala. Doctorul anunta descoperirea printr-o frecventa radio, iar echipa voastra este trimisa intr-o misiune de salvare. Trebuie sa gasiti vaccinul si pe miraculosul doctor datorita intreruperii comunicatiei fara nici o cauza cunoscuta. Aveti la dispozitie doar o ora pana perioada de siguranta se incheie.',
			'room_no3_desc' => 'Porniti spre Insulele Necunoscute in nord-vestul Oceanului Atlantic intr-o misiune data de comandantul Howell Davis pentru a-i gasi comoara. Lasati portul in urma si navigati pe ape misterioase! Sunteti atacati de pirati si majoritatea echipajului este ucis. Cativa sunteti luati prizonieri in pestera piratilor. Piratii pleaca dupa prada si aceasta e sansa voastra pentru a va recapata libertatea! Intrati in lumea piratilor si luati parte la o vanatoare de comori care va ridica adrenalina! Gasiti comoara si descoperiti secretul pesterii piratilor!',
			'room_no4_desc' => 'Ghicitoarea Pietrei Filosofale va trimite intr-o expeditie la periferia unui oras antic din Abusira, Egipt. Aici mitul antic dezvaluie sub pamant o piramida care se crede a fi mormantul marelui Faraon Nyuserre Ini din Dinastia a 5-a. Se zvoneste ca aceasta expeditie i-a costat viata pe exploratorii care cautau comori ascunse. Aventurati-va in labirintul antic si rezolvati mecanismele stravechi pentru a iesi din aceasta ruina sau lasati-va trupurile neinsufletite drept amintire a razbunarii mormantului.',
			
			'login' => 'Conecteaza-te aici',
			'user' => 'Nume de utilizator',
			'pass' => 'Parola',
			'login_button' => 'Conecteaza-te',
			'logout_button' => 'Deconectare',
			'register' => 'Inscrie-te aici',
			'register_button' => 'Inscrie-te',
			'greeting' => 'Bun venit',
			
			'contact_title' => 'Contacteaza-ne',
			'phone_no' => '004 0747 789 245',
			'address' => 'Timisoara B-dul Constantin Brancoveanu 53.',
			'e-mail' => 'office@exitgames.ro',
			'timetable' => 'Program',
			'slot' => '10:00 - 20:00',
			'closed' => 'Inchis',
			'mon' => 'Luni',
			'tue' => 'Marti',
			'wed' => 'Miercuri',
			'thu' => 'Joi',
			'fri' => 'Vineri',
			'sat' => 'Sambata',
			'sun' => 'Duminica',
			
			'booking_title' => 'Completati urmatorul formular',
			'name_field' => 'Nume',
			'email_field' => 'E-mail',
			'phone_field' => 'Telefon',
			'room_field' => 'Camera',
			'date_field' => 'Data',
			'hour_field' => 'Ora',
			'pers_field' => 'Numarul de participanti',
			'price' => 'Preturi',
			'participants' => '2-6 persoane',
			'discount' => 'Happy Hour - inainte de ora 17:00:',
			'price_no1' => '40 lei/persoana',
			'usual' => 'Dupa ora 17:00',
			'price_no2' => '50 lei/persoana',
			'when' => 'Cand sa veniti?',
			'when_ans' => 'Sositi cu 15 minute ininte de inceputul sesiunii.',
			'what' => 'Ce sa aduceti?',
			'what_ans' => 'Curiozitatea si mintea ascutita!',
			'booking_ok' => 'Rezervare efectuata!',
			'total_price' => 'Suma totala: '
			
		)
	);
?>